name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: code_format_check
          pull: default
          image: poetry-image:latest
          commands:
            - pip install yapf
            - pip install toml
            - yapf -dr .
          when:
            event:
              - push


      - name: Install Dependencies
        run: |
            poetry shell
            poetry install

      - name: Build
        run: poetry build