name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: meltwaterfoundation/drone-python3_11-poetry:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: code_format_check
        run: |
          pip install yapf
          pip install toml
          yapf -dr .


      - name: Install Dependencies
        run: |
            poetry shell
            poetry install

      - name: Build
        run: poetry build