name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: meltwaterfoundation/drone-python3_11-poetry:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: code_format_check
        run: |
          pip install yapf
          pip install toml
          yapf -dr .


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --no-dev --no-ansi

      - name: Build
        run: poetry build